# Damn Vulnerable NodeJS Application
# https://github.com/appsecco/dvna

FROM node:18

LABEL MAINTAINER "Subash SN"

WORKDIR /app
RUN node -v
RUN echo "Host geoserver"

RUN npm install -g nodemon

CMD ["/bin/bash", "/app/entrypoint-dev.sh"]
